sonar.projectKey=blog-app
sonar.projectName=BlogApp Microservices
sonar.sources=auth-service,posts-service
sonar.python.version=3.11
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/venv/**,**/node_modules/**,**/__pycache__/**,**/tests/**,**/.next/**,**/dist/**,**/build/**,frontend/**
